### ISSUE TITLE
Add scroll bar and Mouse Row selection support!

### ISSUE THREAD

**Issue by zmcj1** [Almeswe/editor#1]
Hi there,
I successfully compiled your project using VS 2019 and tried it in Windows 10(19043.928), the project gave me a great inspiration about using D2D and DW API. (PS: I'm trying to use these techs to build a new Window Console Renderer)
I hope this editor will continue to improve so that I could to use it instead of FAR Manager's text editor.
    Have a nice day!

**Comment by almeswe** [comment]
Hi, this project was created as a test project for my acquaintance with C++, and i don't think that i wll add something new in it in future.
But I am very glad that it served as a source of your inspiration for learning D2D and DW API, really, thanks!
